### ISSUE TITLE
Does not work correctly for 32-bit x86

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/containment-rpm#35]
```
[  131s] Couldn't find anything in /usr/src/packages/KIWI matching opensuse-tumbleweed-image.i386-1.0.4*.docker.tar.xz.
[  131s] Content of directory: 
[  131s] opensuse-tumbleweed-image.i686-1.0.4-docker-Build9.1.docker.tar.xz
```

**Comment by davidcassany** [comment]
@Vogtinator, I see, looks like https://github.com/SUSE/containment-rpm-docker/blob/f298a7ddaf931ca141fc8d09ba2a00ba1eee9a72/kiwi_post_run#L35 does not return the same values that OBS is using thus the file that `kiwi_post_run` tries to stat does not exist.

I'll see if we can get the arch from some OBS env variable.

**Comment by Vogtinator** [comment]
Kiwi seems to use the value of `platform.machine()` for this, I'm currently trying a patch to use `uname -m` instead of `rpm --eval %_arch`.

**Comment by davidcassany** [comment]
Yes, you are right, we must match KIWI arch values not OBS. Then I'll wait for your patch or feedback, just let us know if you need something.

**Comment by Vogtinator** [comment]
Doesn't seem to be enough:

```
[  152s] Wrote: /usr/src/packages/RPMS/i586/opensuse-tumbleweed-image-1.0.4-0.i586.rpm
[  152s] Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.HlevT2
[  152s] + umask 022
[  152s] + cd /usr/src/packages/BUILD
[  152s] + rm -rf /usr/src/packages/BUILDROOT/opensuse-tumbleweed-image-1.0.4-0.i386
[  152s] + exit 0
[  152s] mv: cannot stat '/usr/src/packages/RPMS/i686/opensuse-tumbleweed-image-1.0.4-0.i686.rpm': No such file or directory
```

Three different arches in there - that'll be annoying.

**Comment by davidcassany** [comment]
Damn, looks like a mess... are you testing this in an accessible repository in OBS?
